### ISSUE TITLE
りんどく.rb を追加したいが、permiddion deniedでpushできない

### ISSUE THREAD

**Issue by Aseiide** [sue445/regional-rb-calendar#139]
@sue445 
お世話になっております。

りんどく.rbというRubyコミュニティを見つけたので`docs/config/connpass.json`に変更を加えて、pushしようとしたところ、以下のようなエラーでpermission dinied となってしまいました。
https://rindokurb.connpass.com/

```shell
remote: Permission to sue445/regional-rb-calendar.git denied to Aseiide.
fatal: unable to access 'https://github.com/sue445/regional-rb-calendar.git/': The requested URL returned error: 403
```

コントリビュートの権限をいただくことは可能でしょうか?
githubアカウントは、@Aseiide です。
よろしくお願いいたします。

**Comment by sue445** [comment]
@Aseiide このリポジトリをforkして自分のリポジトリにpushしてからPullRequestを投げてください。

**Comment by Aseiide** [comment]
@sue445 
cloneしていました。forkしてやり直したいと思います。ありがとうございます！

**Comment by Aseiide** [comment]
PR #140  を作成しましたので、こちらのissueはcloseします。
